rconpwd: "A237822x"
gpttoken: "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"
jwtkey: "A237822x"
allowcmd: ["list"]
mcfont: ""
sql: "backend:backend@tcp(localhost:3306)/backend?charset=utf8mb4&parseTime=True&loc=Local"
