rconpwd: ""
gpttoken: ""
jwtkey: "5201314"
mcfont: /usr/share/fonts/opentype/axo/mc.ttf
sql: backend:Cb8b318b@tcp(192.168.50.38:3306)/userlist?charset=utf8mb4&parseTime=True&loc=Local
serverip: 192.168.50.38
backport: "1314"
avatarpath: ""
ports:
    main: "8000"
    sc: "8001"
    mod: "8002"
serverpath:
    main: /srv/main/
    sc: /srv/sc/
    mod: /srv/mod/
smtpconfig:
    srv: smtp.163.com
    port: 25
    mail: axolotland@163.com
    pwd: FLWEBLGJBWCTAFMV
assistantid:
    gpt3: ""
    gpt4: ""
    axo: ""
