rconpwd: ""
gpttoken: ""
jwtkey: ""
allowcmd:
    - list
    - say
    - tell
    - me
mcfont: /usr/share/fonts/opentype/axo/mc.ttf
sql: backend:backend@tcp(localhost:3306)/backend?charset=utf8mb4&parseTime=True&loc=Local
salt: Axolotland Gaming Club
serverip: 192.168.50.38
port:
    main: ""
    sc: ""
    mod: ""
backport: "1314"
